changed zero based file list to one based file list (0=tty)

diff --git a/yoda b/yoda
--- a/yoda
+++ b/yoda
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# ----- about -------------------------------------------- #FOLD00
+# ----- about -------------------------------------------- #fold00
 # yoda is an acronym of Yet Onather Delirious Application, and does
 # naturally not refer to any greenish midget with pointy ears, albeit
 # it had been said that reading yoda source aloud sounds like the very
@@ -13,7 +13,7 @@
 
 # editor used is efte, folds in source files are therefore efte compatible.
 
-# ----- versions ----------------------------------------- #FOLD00
+# ----- versions ----------------------------------------- #fold00
 # I think we're about ready for approaching version 1.0, so lets start counting.
 # date is post-gregorian Sol3, time is UTC
 # invoke shellcheck with:    shellcheck -x yoda.
@@ -33,7 +33,7 @@ subsubversion=1             #                   early version of automated testi
 #version=0  subversion=2    # 2021dec29,16:04
 #version=0  subversion=1    # 2021dec20,14:57
 
-# ----- declarations ------------------------------------- #FOLD00
+# ----- declarations ------------------------------------- #fold00
 
 shopt -s extglob
 shopt -u nullglob
@@ -88,6 +88,8 @@ done
 declare -a names                                                     # function name -> word name lookup
 declare -A headersunresolved                                         # forward referenced. Not searched.
 declare -A where                                                     # source file, line
+declare -a files
+files[0]="tty"
 declare -A doescode                                                  # items associated with defining word. Detokeniser extracted code
                                                                      # following does> to make it more easily available to dodoes
 declare -a lasterror
@@ -120,7 +122,7 @@ declare -A atom                                                      # a table w
 
 default='from fix  boot quit  "yoda shell" type$ cr  prompt'          # what to execute when no command line args given
 
-# ----- state variables, switches, globals, static etc --- #FOLD00
+# ----- state variables, switches, globals, static etc --- #fold00
 bits=63                                                              # Can't use 64 bit - bash doesn't know unsigned. 63 bit is best I can do for now.
 #bits=32
 #bits=21                                                              # covers 6 decimal digits signed numeric space
@@ -237,7 +239,8 @@ interactive()   {
 header()  {
    lastword="$1"                                                     # global variable. setting header flags needs this one
    (( linenr < 0 )) ||                                               # not entered at keyboard
-      where["$lastword"]="$filenr $linenr"                           # remember file and line nr
+      where["$lastword"]="${filenr:-1} $linenr"                           # remember file and line nr
+# echo "header $1: filenr=${filenr:-1}"
    [[ -z "${headersstateless["$1"]}" ]] ||  {
       [[ ${headersstateless["$1"]} == "${header_code}_"* ]] &&
          echo "redefining $1"
@@ -249,7 +252,7 @@ header()  {
 }
 
 
-# ----- pretend optimiser -------------------------------- #FOLD00
+# ----- pretend optimiser -------------------------------- #fold00
 # currently only a detokeniser. Plugged preparing further use.
 # The way it works:
 #    when a word gets compiled to a function, it will first be
@@ -339,7 +342,7 @@ optimise()  {                                                        # run code 
    }
 }
 
-# ----- line parser -------------------------------------- #FOLD00
+# ----- line parser -------------------------------------- #fold00
 
 # these need extglobs, set with "shopt -s extglob"
 
@@ -367,7 +370,7 @@ parse()  {
    line="${line#"$1"}"
 }
 
-# ----- compiler ----------------------------------------- #FOLD00
+# ----- compiler ----------------------------------------- #fold00
 
 # atoms may be:
 #  - micro instructions
@@ -418,7 +421,7 @@ stateless()   {
 }
 
 
-# ----- defining words ----------------------------------- #FOLD00
+# ----- defining words ----------------------------------- #fold00
 
 
 # make stack effect of word known, aiding the optimiser
@@ -439,13 +442,6 @@ push()  {
 }
 
 
-# --- pending change of "where" ---
-#  file=0:  console
-#  file=1:  first loaded file (yoda)
-#  currently, file 0 refers to yoda, ${files[0]}
-# affects:  file$ where$ #files
-
-
 # quite some factoring possible in this section
 # arg1: word name
 create()  {
@@ -462,7 +458,7 @@ create()  {
 #   analyser=()                                                      # reinitialise code tags for analyser
 
    [[ -z "$linenr" ]] &&
-      where["$lastword"]="0 ${BASH_LINENO[0]}"                       # remember file and line number
+      where["$lastword"]="1 ${BASH_LINENO[0]}"                       # remember file and line number
 }
 
 
@@ -483,7 +479,7 @@ colon()  {
 primitive()  {
    create "$1"
    [[ -z "$linenr" ]] &&
-      where["$lastword"]="0 ${BASH_LINENO[0]}"                       # remember file and line number
+      where["$lastword"]="1 ${BASH_LINENO[0]}"                       # remember file and line number
    inline
    use "$2"
 }
@@ -506,8 +502,7 @@ primitive()  {
 #      echo "-- ${FUNCNAME[@]:0:4}"
       [[ "${FUNCNAME[2]}" == "evaluate" ]] &&
          tmp="${BASH_LINENO[2]}"
-#      echo "-- $lastword: 0 $tmp"
-      where["$lastword"]="0 $tmp"
+      where["$lastword"]="1 $tmp"
    }
 
 #   code "$1" "$functionheader"                                      # preparing to delegate header creation to detokeniser
@@ -527,6 +522,12 @@ semicolon()  {
 }                                                                    # a function created from contents of array.
 
 
+# should be possible to save several where[]=... assignments by calling a
+# single common word, rather than a chain of nested calls.
+# may also simplify to use two hashes, wherefile and whereline, rather than
+# storing a data pair per item, as it becomes easier to deal with each data
+# portion individually
+
 constant()  {
    colon "$1"
    push "$2"
@@ -534,7 +535,7 @@ constant()  {
    inline
    inout 0 1
    [[ -z "$linenr" ]] &&
-      where["$lastword"]="0 ${BASH_LINENO[0]}"                       # remember file and line number
+      where["$lastword"]="1 ${BASH_LINENO[0]}"                       # remember file and line number
 }
 
 
@@ -544,7 +545,7 @@ variable()  {
    m[dp]="${2:-0}"
    constant "$1" "$((dp++))"
    [[ -z "$linenr" ]] &&
-      where["$lastword"]="0 ${BASH_LINENO[0]}"                       # remember file and line number
+      where["$lastword"]="1 ${BASH_LINENO[0]}"                       # remember file and line number
 }
 
 
@@ -567,7 +568,7 @@ constant 'bits'               "$bits"
 
 
 
-# ----- errors, traps, entry points----------------------- #FOLD00
+# ----- errors, traps, entry points----------------------- #fold00
 
 warm()  {
    line=""                                                           # signal to evaluate to stop evaluation of current line
@@ -654,7 +655,7 @@ trap ctrl-c SIGINT
 
 
 
-# ----- patterns ----------------------------------------- #FOLD00
+# ----- patterns ----------------------------------------- #fold00
 
 declare -A bases=(['%']=2 ['#']=10 ['$']=16)
 pattern()  {                                                         # pattern interpreted as
@@ -731,7 +732,7 @@ pattern()  {                                                         # pattern i
 }
 
 
-# ----- resolve forward refs ----------------------------- #FOLD00
+# ----- resolve forward refs ----------------------------- #fold00
 
 # total headers count is used to help determining if resolving
 # forward refs create new forward refs, in which case resolving
@@ -860,16 +861,20 @@ evaluate()  {
 
 
 
-# ----- load source files -------------------------------- #FOLD00
+# ----- load source files -------------------------------- #fold00
 
 # return filenr pointing to matching file in array files,
 # or to end of array where new file will be added if no
-# matching file was found
+# matching file was found. Also return a return values (1)
+# if not loaded, return 0 when loaded.
+# (seems twisted but allows condition  "if loaded; then ..."
+
 loaded()  {
    local file="$1"
-   for ((filenr=0; filenr<${#files[@]}; filenr++)); do               # while multiple inclusion is allowed, those files won't be recorded multiple times
+   for ((filenr=1; filenr<${#files[@]}; filenr++)); do               # while multiple inclusion is allowed, those files won't be recorded multiple times
       [[ "${files[filenr]}" == "$file" ]] && break                   # so when already recorded, break out
    done
+   return $(( filenr >= ${#files[@]}))
 }
 
 # nestable source include
@@ -892,7 +897,7 @@ from()  {
    [[ -f "$file" ]] || return 1                                      # not found
    file="$(realpath "$file")"                                        # canonical or original name of file
 
-   loaded "$file"
+   loaded "$file"                                                    # need not for check, but for filenr
 
 # mark  (headers counts of all vocabularies)
 # error must  forget (reset to last mark)
@@ -914,7 +919,8 @@ from()  {
 # this should for now have some adverse effects on words
 # compiled from files with errors. They may, for example,
 # point to wrong or non-existing source file.
-   (( filenr < ${#files[@]} )) || { files+=("$file"); }              # first time inclusion: add to files array
+# echo "from:  filenr=$filenr, file=$file"
+   (( filenr < ${#files[@]} )) || { files[filenr]="$file"; }       # first time inclusion: add to files array
 
 
    (( ${#headersunresolved[@]} )) && {                               # any forward references created?
@@ -926,7 +932,7 @@ from()  {
 
 
 
-# ----- primitives --------------------------------------- #FOLD00
+# ----- primitives --------------------------------------- #fold00
 # ----- populating detokeniser --------------------------- #fold01
 # for testing, a handful of inlined single operation primitives
 # and atomic operations are added. no optimising take place now.
@@ -1066,7 +1072,7 @@ primitive 'see' 'see'
 primitive '.s' '((sp))&&printf "%s " "${s[@]:1:$sp}"'
 
 
-# ----- does> -------------------------------------------- #FOLD01
+# ----- does> -------------------------------------------- #fold01
 
 # compiled to the end of a defining word,
 # is therefore called by create part, and
@@ -1091,7 +1097,7 @@ dodoes()  {                                                          # append do
 # approaches I was thinking of.
 primitive 'does>'  'code "dodoes" "$does"';   immediate
 
-# ----- defining words ----------------------------------- #FOLD01
+# ----- defining words ----------------------------------- #fold01
 
 # essentially a constant with yet to be specified source for its
 # value and overwritable run time semantics (push value by default)
@@ -1119,7 +1125,7 @@ colon "array"
    code "((dp+=s[sp--]))"                                            # allocate
 semicolon
 
-# ----- compiler and word search related ----------------- #FOLD01
+# ----- compiler and word search related ----------------- #fold01
 
 # ( -- 0 | a )
 have() {
@@ -1189,7 +1195,7 @@ primitive '#unresolved' '((s[++sp]=${#headersunresolved[@]}))'       # ( -- u )
 primitive 'recurse' 'code "${headersstateless["$lastword"]}"'; immediate   # ( -- )
 
 
-# ----- environment--------------------------------------- #FOLD01
+# ----- environment--------------------------------------- #fold01
 # read number from environment variable with name on string stack
 # ( -- x )  ( string:  $1 -- )
 colon 'env'
@@ -1234,7 +1240,7 @@ primitive '('    "parse ')'"; immediate
 primitive '('    "parse ')'"; interactive
 
 
-# ----- parameter stack ---------------------------------- #FOLD01
+# ----- parameter stack ---------------------------------- #fold01
 
 
 colon 'dup'
@@ -1337,7 +1343,7 @@ inline
 primitive 'depth'  '((s[++sp]=$sp))'
 primitive 'pick'   '((s[++sp]=s[sp-s[sp]]))'
 
-# ----- return stack ------------------------------------- #FOLD01
+# ----- return stack ------------------------------------- #fold01
 
 colon 'r@'
    atom 'r@'
@@ -1384,7 +1390,7 @@ inout 0 1
 
 primitive 'rdepth'  '((s[++sp]=rp))'; inout 0 1
 
-# ----- string stack ------------------------------------- #FOLD01
+# ----- string stack ------------------------------------- #fold01
 
 primitive 'depth$'   's+=("${#ss[@]}")'
 primitive 'empty$'   'ss=()'
@@ -1600,7 +1606,7 @@ evaluate "' lshift alias <<"
 evaluate "' rshift alias >>"
 colon    'invert';  atom 'invert'; semicolon; inline
 
-# ----- comparison --------------------------------------- #FOLD01
+# ----- comparison --------------------------------------- #fold01
 
 primitive '0='   '((s[sp]=s[sp]?0:maxuint))'                         # 0->maxuint  x->0
 primitive '0<>'  '((s[sp]=s[sp]?maxuint:0))'                         # 0->0   x->maxuint
@@ -1669,7 +1675,7 @@ inout 4 1
 
 
 
-# ----- arithmetics -------------------------------------- #FOLD01
+# ----- arithmetics -------------------------------------- #fold01
 
 colon '1+'
    atom '1+'
@@ -1888,7 +1894,7 @@ move()  {                                                            # deals wit
 # ( a1 a2 u -- )
 primitive 'move'   'move'; inout 3 0
 
-# ----- flow control ------------------------------------- #FOLD01
+# ----- flow control ------------------------------------- #fold01
 
 remagic
 
@@ -2068,7 +2074,7 @@ colon '?abort'
 semicolon
 
 
-# ----- conditional compilation--------------------------- #FOLD01
+# ----- conditional compilation--------------------------- #fold01
 
 # need can create forward ref even though forward refs are turned off.
 # resolving will still be done, that way can specific words (and their
@@ -2095,7 +2101,7 @@ semicolon
 
 primitive 'have'   'have'
 evaluate ': lack  have 0= ;'
-# ----- i/o ---------------------------------------------- #FOLD01
+# ----- i/o ---------------------------------------------- #fold01
 
 colon 'esc['
    code 'printf "\e[%s" "${ss[-1]}"'
@@ -2217,7 +2223,7 @@ semicolon
 
 evaluate ': from word from$ ;'
 primitive '#files' '((s[++sp]=${#files[@]}))'; inout 0 1
-primitive 'files'  'printf "%s\n" "${files[@]}"|nl'                             # show list of already included files
+primitive 'files'  'printf "%s\n" "${files[@]}"|nl -v 0'                             # show list of already included files
 
 # ----- pictured number conversion ----------
 
@@ -2262,7 +2268,7 @@ inout 0 1
 
 
 
-# ----- documentation ------------------------------------ #FOLD01
+# ----- documentation ------------------------------------ #fold01
 
 
 undoc_template()  {
@@ -2374,7 +2380,7 @@ primitive 'help' 'helptext'
 
 evaluate ': quit warm begin query$ evaluate$ prompt again ;'
 
-# ----- convenience -------------------------------------- #FOLD01
+# ----- convenience -------------------------------------- #fold01
 # TODO: optimiser: invalidate all stack register contents
 # execute shell command "$2" with args "$1"
 colon 'command$'
@@ -2393,14 +2399,8 @@ primitive 'random' '((s[++sp]=RANDOM&maxuint))'; inout 0 1                 # ( -
 primitive 'realtime' '((s[++sp]=${EPOCHREALTIME//,/}&maxuint))'; inout 0 1 # a microseconds epoch, used for benchmarking
 primitive 'secs' 'sleep "${s[sp--]}"'
 
-# sort out file handles to make 1+ / 1- offsetting unnecessary
 colon 'file$'
-   code '((tmp=s[sp--]))'
-   code 'if ((tmp)); then'
-   code 'ss+=("${files[tmp-1]}")'                            # ( u -- ) ( string: -- $1 ) push name of file u (from output of files) to string stack
-   code 'else'
-   code 'ss+=("")'                                           # ( u -- ) not sure what to do with console
-   code 'fi'
+   code 'ss+=("${files[s[sp--]]}")'                            # ( u -- ) ( string: -- $1 ) push name of file u (from output of files) to string stack
 semicolon
 
 evaluate ': edit  "editor" file$  command$ ;'
@@ -2423,7 +2423,7 @@ inout 2 2
 # whether it was loaded already, to conditionally end loading (through done)
 # ( -- u )
 colon 'source'
-   push '${filenr:-"-1"}+1'
+   push '${filenr:-"0"}'
 semicolon
 inline
 inout 0 1
@@ -2436,7 +2436,7 @@ evaluate ': loaded  ( -- f )  source file$ count$ 0<> ;'
 
 
 
-# ----- experimental ------------------------------------- #FOLD01
+# ----- experimental ------------------------------------- #fold01
 
 # stop loading file
 colon 'done'
@@ -2476,7 +2476,7 @@ colon 'where$'
     code '[[ -z $tmp ]]&&emptyname'
     code 'tmp1="${where[$tmp]}"'
     code '[[ -z $tmp1 ]]&&notfound "$tmp"'
-    push '${where[${ss[-1]}]%% *}+1'
+    push '${where[${ss[-1]}]%% *}'
     push '${where[${ss[-1]}]#* }'
 semicolon
 
@@ -2497,7 +2497,7 @@ evaluate ': where word where$ swap file$ type$ [char] : emit  u. ;'
 # shellcheck source=./yoda.conf                                      # try to load custom configuration
 [[ -f "$mydir/$config" ]] && source "$mydir/$config"                 # currently only looking in dir where yoda resides
 args=("$@")
-files[0]="$(realpath "$0")"
+files[1]="$(realpath "$0")"
 ((${#args[@]})) || args[0]="$default"
 evaluate "${args[*]}"
 if [[ -n "$coldvector" ]]; then                                      # if cold launch point was specified, try to run.
